ui:
  time_format: 24hour

mqtt:
  enabled: false

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

audio:
  enabled: true
  listen:
    - yell
    - music
    - scream
    - speech

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detect:
  enabled: true
  fps: 10

notifications:
  enabled: true
  email: frigate@ccrsxx.com

record:
  enabled: true
  retain:
    days: 30
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

semantic_search:
  enabled: true
  reindex: false
  model_size: large

genai:
  enabled: true
  provider: gemini
  api_key: '{FRIGATE_GEMINI_API_KEY}'
  model: gemini-2.5-flash

go2rtc:
  webrtc:
    candidates:
      - 192.168.1.100:8555
      - stun:8555
  streams:
    bedroom_cam:
      - '{FRIGATE_RTSP_CAM_BEDROOM}'
      - '{FRIGATE_ISAPI_CAM_BEDROOM}'
      - 'ffmpeg:bedroom_cam#audio=opus'
    bedroom_cam_sub:
      - '{FRIGATE_RTSP_CAM_BEDROOM_SUB}'
      - 'ffmpeg:bedroom_cam_sub#audio=opus'
    kitchen_cam:
      - '{FRIGATE_RTSP_CAM_KITCHEN}'
      - '{FRIGATE_ISAPI_CAM_KITCHEN}'
      - 'ffmpeg:kitchen_cam#audio=opus'
    kitchen_cam_sub:
      - '{FRIGATE_RTSP_CAM_KITCHEN_SUB}'
      - 'ffmpeg:kitchen_cam_sub#audio=opus'

cameras:
  bedroom_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom_cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bedroom_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    genai:
      enabled: false
    notifications:
      enabled: true
  kitchen_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen_cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kitchen_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    genai:
      enabled: true
    notifications:
      enabled: true

version: 0.16-0
