services:
  actual-budget:
    image: actualbudget/actual-server:latest
    container_name: actual-budget
    ports:
      - '5006:5006'
    volumes:
      - /docker/appdata/actual-budget:/data
    restart: unless-stopped
    environment:
      - ACTUAL_OPENID_ENFORCE=true
