http:
  routers:
    jellyfin:
      rule: Host(`jellyfin.{{ env "DOMAIN_MAIN_PRIMARY" }}`)
      service: jellyfin
      middlewares:
        - allow-id-ips
        - rate-limit
        - tinyauth@docker

    jellyfin-preflight:
      rule: Host(`jellyfin.{{ env "DOMAIN_MAIN_PRIMARY" }}`) && Method(`OPTIONS`)
      service: jellyfin
      middlewares:
        - allow-id-ips
        - rate-limit

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://wg-easy:8096
