http:
  routers:
    jellyfin:
      rule: Host(`jellyfin.{{ env "DOMAIN_MAIN_PRIMARY" }}`)
      service: jellyfin
      middlewares:
        - allow-id-ips
        - jellyfin-rate-limit
        - tinyauth@docker

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://wg-easy:8096
