services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1
    restart: unless-stopped
    ports:
      - 1411:1411
    volumes:
      - '/docker/appdata/pocket-id:/app/data'
    environment:
      - APP_URL=${APP_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - PUID=${PUID}
      - PGID=${PGID}
      - TRUST_PROXY=${TRUST_PROXY}
    healthcheck:
      test: ['CMD', '/app/pocket-id', 'healthcheck']
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
