services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    container_name: jellyfin
    network_mode: 'host'
    group_add:
      - 104
    volumes:
      - /docker/appdata/jellyfin/config:/config
      - /mnt/docker/appdata/jellyfin/cache:/cache
      - /mnt/data/media:/data/media:ro
      - /mnt/data/torrents:/data/torrents:ro
      - ./patch.sh:/patch.sh:ro
    entrypoint: /patch.sh
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-false}'
      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_MAIN_PRIMARY}`) || Host(`jellyfin.${DOMAIN_MAIN_SECONDARY}`)'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'
