http:
  middlewares:
    lidarr-theme:
      plugin:
        themepark:
          app: lidarr
          theme: hotline

    bazarr-theme:
      plugin:
        themepark:
          app: bazarr
          theme: hotline

    radarr-theme:
      plugin:
        themepark:
          app: radarr
          theme: hotline

    sonarr-theme:
      plugin:
        themepark:
          app: sonarr
          theme: hotline

    prowlarr-theme:
      plugin:
        themepark:
          app: prowlarr
          theme: hotline

    adguard-home-theme:
      plugin:
        themepark:
          app: adguard
          theme: hotline

    qbittorrent-theme:
      plugin:
        themepark:
          app: vuetorrent
          theme: hotline
